# Generated by Django 3.2.5 on 2021-08-08 14:49

from django.db import migrations, models
import video_to_audio.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_to_audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to=video_to_audio.models.rename_and_save),
        ),
    ]
