# Generated by Django 3.2.5 on 2021-08-08 14:52

import django.core.validators
from django.db import migrations, models
import video_to_audio.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_to_audio', '0002_alter_videomodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to=video_to_audio.models.rename_and_save, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'wmv', 'flv', 'avi', 'avchd', 'webm'])]),
        ),
    ]
